name: flutter_application_2
description: "koombiyo staff app."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+35


environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_sizer: ^1.0.5
  flutter_staggered_animations: ^1.1.1
  provider: ^6.1.1
  page_transition: ^2.1.0
  intl: 
  flutter_share:
  geolocator: ^10.1.0
  curved_labeled_navigation_bar:
  fl_chart: ^0.66.0
  lottie: 
  otp_text_field: ^1.1.3
  # sms_autofill: ^2.3.0
  loading_animation_widget: ^1.2.0+4
  google_maps_flutter:
  url_launcher: 
  flutter_barcode_scanner: ^2.0.0
  dotted_border: ^2.1.0
  image_picker: ^1.0.7
  top_snackbar_flutter: ^3.1.0
  # awesome_dialog: ^3.2.0
  connectivity_plus: ^5.0.2
  internet_connection_checker: 
  shared_preferences: ^2.2.2
  http: 
  app_install_date: ^0.1.3
  path_provider: ^2.1.2
  badges: ^3.1.2
  permission_handler:
  dio: ^5.4.0
  telephony:
  toggle_switch: ^2.1.0
  # video_player: ^2.8.2
  # chewie:
  youtube_player_flutter: ^9.0.0
  dropdown_button2: ^2.3.9
  quickalert: ^1.0.2
  in_app_review: ^2.0.8
  animated_icon: 
  gauge_indicator: ^0.4.3
  icons_launcher: ^2.1.7
  shimmer: ^3.0.0
  html: ^0.15.4
  flutter_launcher_icons: ^0.13.1
  simple_ripple_animation: ^0.0.9
  circular_reveal_animation: ^2.0.1
  signature: ^5.4.1
  pdf:
  printing: ^5.12.0
  firebase_core: ^2.14.0
  firebase_messaging: ^14.7.19
  # flutter_local_notifications: ^17.0.0
  awesome_notifications: ^0.9.3+1
  latlong2: ^0.9.1
  expansion_tile_group:
  timeline_tile: ^2.0.0
  timelines: ^0.1.0
  font_awesome_flutter: ^10.7.0
  qr_code_scanner: ^1.0.1
  flutter_map: 
  flutter_map_location_marker:
  sqflite:
  keyboard_hider: 
  flutter_ringtone_player:
  scannabletextformfield: ^0.1.0
  carousel_slider:
  flutter_chat_bubble:
  logger:
  flutter_polyline_points:

 


 
 
  # syncfusion_flutter_maps: ^26.1.40

  # zego_uikit_prebuilt_call: ^4.9.0
  # zego_uikit: ^2.22.2
  # zego_zpns: ^2.2.0
  
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Delivery Logo-06.jpg"
  min_sdk_android: 21 
  adaptive_icon_background: "#1c1c1a"
  
  


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-VariableFont_slnt,wght.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: KodeMono
      fonts:
        - asset: fonts/KodeMono-VariableFont_wght.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
